Controllers/HomeController.cs
using CrickAuctioner.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CrickAuctioner.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        [Authorize]
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PlayerAccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CrickAuctioner.Data;
using CrickAuctioner.Models;
using System.Globalization;

namespace CrickAuctioner.Controllers
{
    public class PlayerAccountsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PlayerAccountsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: PlayerAccounts
        public async Task<IActionResult> Index()
        {
           return View(await _context.PlayerAccount.ToListAsync());
        }

        // GET: PlayerAccounts
        public async Task<IActionResult> PLogin()
        {
            return View(await _context.PlayerAccount.ToListAsync());
        }

        // GET: PlayerAccounts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.PlayerAccount == null)
            {
                return NotFound();
            }

            var playerAccount = await _context.PlayerAccount
                .FirstOrDefaultAsync(m => m.PlayerId == id);
            if (playerAccount == null)
            {
                return NotFound();
            }

            return View(playerAccount);
        }

        // GET: PlayerAccounts/Create
        public IActionResult Create()
        {
            return View();
        }

        // GET: PlayerAccounts/Create
        public IActionResult Register()
        {
            return View();
        }

        // POST: PlayerAccounts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register([Bind("PlayerId,PlayerName,PlayerEmail,PlayerDOB,Password,ConfirmPassword,PlayerCountry,CreatedOn")] PlayerAccount playerAccount)
        {
            if (ModelState.IsValid)
            {
                _context.Add(playerAccount);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(PLogin));
            }
            return View(playerAccount);
        }

        // POST: PlayerAccounts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PlayerId,PlayerName,PlayerEmail,PlayerDOB,Password,ConfirmPassword,PlayerCountry,CreatedOn")] PlayerAccount playerAccount)
        {
            if (ModelState.IsValid)
            {
                _context.Add(playerAccount);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(playerAccount);
        }

        // GET: PlayerAccounts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.PlayerAccount == null)
            {
                return NotFound();
            }

            var playerAccount = await _context.PlayerAccount.FindAsync(id);
            if (playerAccount == null)
            {
                return NotFound();
            }
            return View(playerAccount);
        }

        // POST: PlayerAccounts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PlayerId,PlayerName,PlayerEmail,PlayerDOB,Password,ConfirmPassword,PlayerCountry,CreatedOn")] PlayerAccount playerAccount)
        {
            if (id != playerAccount.PlayerId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(playerAccount);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PlayerAccountExists(playerAccount.PlayerId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(playerAccount);
        }

        // GET: PlayerAccounts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.PlayerAccount == null)
            {
                return NotFound();
            }

            var playerAccount = await _context.PlayerAccount
                .FirstOrDefaultAsync(m => m.PlayerId == id);
            if (playerAccount == null)
            {
                return NotFound();
            }

            return View(playerAccount);
        }

        // POST: PlayerAccounts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.PlayerAccount == null)
            {
                return Problem("Entity set 'ApplicationDbContext.PlayerAccount'  is null.");
            }
            var playerAccount = await _context.PlayerAccount.FindAsync(id);
            if (playerAccount != null)
            {
                _context.PlayerAccount.Remove(playerAccount);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PlayerAccountExists(int id)
        {
          return _context.PlayerAccount.Any(e => e.PlayerId == id);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4"><b>Crick</b>Auctioner</h1>

    <div class="row">
        <div class="col">
            <div class="card" style="width: 18rem;">
                <img class="card-img-top" src="~/images/ipl.png" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">Player Registration Open for IPL </h5>
                    <p class="card-text">Apply for IPL 2023 Season Now</p>
                     <a class="btn btn-primary" asp-area="" asp-controller="PlayerAccounts" asp-action="Register">Apply</a>
                </div>
            </div>
        </div>

        <div class="col">
            <div class="card" style="width: 18rem;">
                <img class="card-img-top" src="~/images/bbl.png" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">Player Registration Open for Big Bash Legue</h5>
                    <p class="card-text">Apply for BBL 2023 Season Now</p>
                     <a class="btn btn-primary" asp-area="" asp-controller="PlayerAccounts" asp-action="Register">Apply</a>
                </div>
            </div>
        </div>

        <div class="col">
            <div class="card" style="width: 18rem;">
                <img class="card-img-top" src="~/images/lpl.png" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">Player Registration Open for LPL 2022</h5>
                    <p class="card-text">Apply for LPL 2022 Season Now</p>
                    <a class="btn btn-primary" asp-area="" asp-controller="PlayerAccounts" asp-action="Register">Apply</a>
                </div>
            </div>
        </div>

        <div class="col">
            <div class="card" style="width: 18rem;">
                <img class="card-img-top" src="~/images/psl.png" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">Card title</h5>
                    <p class="card-text">Apply for IPL 2023 Season Now</p>
                     <a class="btn btn-primary" asp-area="" asp-controller="PlayerAccounts" asp-action="Register">Apply</a>
                </div>
            </div>
        </div>


    </div>


</div>